const fs = require('fs');
const digest = fs.readFileSync('context/DAILY_DIGEST.md', 'utf8');
const checks = {
  'No_Generated_on': !/Generated on:/i.test(digest),
  'No_dynamic_date': !/generated\s+on\s*:\s*\d{4}-\d{2}-\d{2}/gi.test(digest),
  'No_absolute_paths': !digest.includes('/Users/'),
  'Contains_generator_header': digest.includes('Generated by**: CentralContext Daily Digest Generator')
};
for (const [k,v] of Object.entries(checks)) {
  console.log(k + ':', v ? 'PASS' : 'FAIL');
  if (!v) process.exit(1);
}
console.log('All digest format checks passed.');
